spring:
  profiles: local
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017
 # mail:
  #  host:
   # username:
    #password:
    #properties:
     # mail:
      #  transport:
       #   protocol:
        #smtp:
         # port:
          #auth:
          #starttls:
           # enable:
            #required:

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

        security: DEBUG

twilio:
  sid: AC76878a21d8cffbdd9a98c53521a65cda
  token: 23c0cb9e5f55f477a64f452de882e1c5
  number: +14074557061