spring:
  profiles: local
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

        security: DEBUG